# Generated by Django 5.1.7 on 2025-03-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_userclaims_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='weathercondition',
            name='condition',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='description',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
