# Generated by Django 5.1.6 on 2025-02-19 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='claimtrainingdata',
            name='weather_conditions',
        ),
        migrations.AlterField(
            model_name='claimtrainingdata',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.vehicletype'),
        ),
        migrations.AlterField(
            model_name='userclaims',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.vehicletype'),
        ),
        migrations.AddField(
            model_name='claimtrainingdata',
            name='weather_condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_app.weathercondition'),
        ),
        migrations.AlterField(
            model_name='userclaims',
            name='weather_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.weathercondition'),
        ),
    ]
