# Generated by Django 5.1.6 on 2025-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclaims',
            name='injury_prognosis_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userclaims',
            name='police_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclaims',
            name='witness_present',
            field=models.BooleanField(default=False),
        ),
    ]
